version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
    groups:
      typescript-eslint:
        patterns:
         - '@typescript-eslint/*'
