name: Extension Publisher

on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Git setup
        run: |
            git --version
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Obtain tag
        run: |
            LAST_TAG=$(git describe --tags --abbrev=0)
            sed "s/v//" <<< "$LAST_TAG" | IFS=. read -r MAJOR MINOR PATCH 
      - name: Increment patch
        run:  |
            ((PATCH++))
      - name: Replace version
        run: |
            # Replace version in package.json
            NEW_TAG="v$MAJOR.$MINOR.$PATCH"
            sed -i "s/$LAST_TAG/$NEW_TAG/" package.json
            
            # Add tag to the manifest
            cat public/updates.json | python3 -c "import sys, json; \
            f = json.load(sys.stdin); \
            k = f['addons']['quizletbypass@rospino74.github.io']['updates']; \
            i = k[-1].copy(); \
            i['version'] = '$NEW_TAG'[1:]; \
            i['update_link'] = i['update_link'].replace('$LAST_TAG', '$NEW_TAG'); \
            k.append(i); \
            print(json.dumps(f, indent = 4))" > public/updates.json
      - name: Commit
        run: |
            git commit -am "$NEW_TAG"
            git tag -a "$NEW_TAG"
            git push
