name: Extension Publisher

on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Git setup
        run: |
            git --version
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - run: cat public/updates.json
      - name: Version upgade
        run: |
            LAST_TAG=$(git describe --tags --abbrev=0 | sed "s/v//")
            IFS="." read MAJOR MINOR PATCH <<< "$LAST_TAG" # Tricky hack to make bash happy :)
            
            ((PATCH++))
            NEW_TAG="$MAJOR.$MINOR.$PATCH"
           
            # Replace version in package.json
            sed -i "s/\"version\": \"$LAST_TAG\"/\"version\": \"$NEW_TAG\"/" package.json
            
            # Add tag to the manifest
            cat public/updates.json | python3 -c "import sys, json; \
            f = json.load(sys.stdin); \
            k = f['addons']['quizletbypass@rospino74.github.io']['updates']; \
            i = k[-1].copy(); \
            i['version'] = '$NEW_TAG'; \
            i['update_link'] = i['update_link'].replace('v$LAST_TAG', 'v$NEW_TAG'); \
            k.append(i); \
            print(json.dumps(f, indent = 4))" > public/updates.json
      - name: Commit and Push
        run: |
            git commit -am "v$NEW_TAG"
            git tag -a "v$NEW_TAG"
            git git push origin HEAD "v$NEW_TAG"
